import { jsPDF } from "jspdf";
import type { GenerationWithQuestions } from "@/types";

export const generatePdf = async (
  generation: GenerationWithQuestions
): Promise<void> => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = margin;

  const lineHeight = {
    title: 8,
    normal: 5,
    question: 6,
  };

  const addNewPageIfNeeded = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
  };

  const renderWrappedText = (
    text: string,
    x: number,
    maxWidth: number,
    lineHeightValue: number
  ): number => {
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, yPosition);
    return lines.length * lineHeightValue;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);

  const titleHeight = renderWrappedText(
    generation.sourceName,
    margin,
    contentWidth,
    lineHeight.title
  );
  yPosition += titleHeight + 4;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);

  const metaText = `${generation.questionCount} Questions  •  ${generation.difficulty}  •  Generated by ExamGen`;
  const metaHeight = renderWrappedText(
    metaText,
    margin,
    contentWidth,
    lineHeight.normal
  );
  yPosition += metaHeight + 10;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  generation.questions?.forEach((question, index) => {
    addNewPageIfNeeded(60);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);

    const questionText = `${index + 1}. ${question.questionText}`;
    const questionHeight = renderWrappedText(
      questionText,
      margin,
      contentWidth,
      lineHeight.question
    );
    yPosition += questionHeight + 8;

    const optionKeys = ["A", "B", "C", "D"] as const;
    const optionIndent = margin + 8;
    const optionMaxWidth = contentWidth - 12;

    optionKeys.forEach((key) => {
      addNewPageIfNeeded(20);

      const optionText = question.options[key];
      const isCorrect = question.correctAnswer === key;

      doc.setFontSize(11);

      if (isCorrect) {
        doc.setTextColor(22, 163, 74);
        doc.setFont("helvetica", "bold");
      } else {
        doc.setTextColor(71, 85, 105);
        doc.setFont("helvetica", "normal");
      }

      const prefix = `${key})  `;
      const suffix = isCorrect ? "  [Correct Answer]" : "";
      const fullOptionText = `${prefix}${optionText}${suffix}`;

      const optionHeight = renderWrappedText(
        fullOptionText,
        optionIndent,
        optionMaxWidth,
        lineHeight.normal
      );

      yPosition += optionHeight + 4;
    });

    yPosition += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    const explanationText = `Explanation: ${question.explanation}`;
    const explanationLines = doc.splitTextToSize(
      explanationText,
      contentWidth - 14
    );
    const explanationHeight = explanationLines.length * lineHeight.normal + 12;

    addNewPageIfNeeded(explanationHeight + 10);

    doc.setFillColor(239, 246, 255);
    doc.roundedRect(
      margin,
      yPosition,
      contentWidth,
      explanationHeight,
      2,
      2,
      "F"
    );

    doc.setTextColor(30, 64, 175);
    doc.text(explanationLines, margin + 7, yPosition + 8);

    yPosition += explanationHeight + 12;

    if (index < (generation.questions?.length || 0) - 1) {
      addNewPageIfNeeded(15);
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 12;
    }
  });

  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.setFont("helvetica", "italic");

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(
      `Page ${i} of ${pageCount}  •  Generated by ExamGen`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  const fileName = generation.sourceName
    .replace(/[^a-z0-9]/gi, "_")
    .replace(/_+/g, "_")
    .slice(0, 50)
    .toLowerCase();

  doc.save(`${fileName}_examgen.pdf`);
};
